apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: picpay-api
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picpay-api
  template:
    metadata:
      labels:
        app: picpay-api
    spec:
      containers:
        - name: api
          image: eneiasmedina/easypicpay-api:a0a68aaa34c9825b5845d6b750b75e443a3f1aa6
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: easypicpay-secrets
                  key: ConnectionStrings__DefaultConnection
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: easypicpay-secrets
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: easypicpay-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: easypicpay-secrets
                  key: Jwt__Audience
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 1m}
        - setWeight: 50
        - pause: {duration: 1m}
        - analysis:
            templates:
              - templateName: success-rate