apiVersion: apps/v1
kind: Deployment
metadata:
  name: picpay-api
  labels:
    app: picpay-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picpay-api
  template:
    metadata:
      labels:
        app: picpay-api
    spec:
      containers:
      - name: api
        image: picpay-api:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080