# Aplique via kubectl ou edite no painel do ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: picpay-api-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/medinasp/k8s-easy-picpay.git
    targetRevision: HEAD
    path: apps/picpay-api/overlays/prod
    # NÃO colocar token aqui! O segredo cuida disso.